sudo: required
dist: trusty

language: node_js
node_js:
  - "8"
  - "10"

addons:
 chrome: stable

before_install:
 - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222

install:
  - npm install

script:
  - npm test
